using System.Collections.Generic;

internal sealed partial class MinecraftDialogue
{
    private static void AddUndergroundBiomes(Dictionary<string, Line[]> d)
    {
        Biome(d, "dripstone_caves",
            "Мы в карстовых пещерах. Осторожнее с острыми натёками!|We're in dripstone caves. Watch out for the pointed dripstone!",
            "Натёки сверху и снизу. Здесь лучше смотреть под ноги.|Dripstone above and below. Best watch our footing here.",
            "В карстовых пещерах столько каменных игл! Выберем безопасный путь.|So many stone spikes in these dripstone caves! Let's find a safe route.",
            "Карстовые пещеры впечатляют, но прыгать здесь стоит осторожно.|Dripstone caves are impressive, but let's be careful with jumps.",
            "Летим через карстовые пещеры. Берегись натёков!|We're flying through dripstone caves. Watch for the spikes!",
            "В полёте между натёками нужно оставить запас места.|We'll need room to spare while flying between the dripstone.",
            "Карстовые пещеры на пути. Не зацепим каменные иглы.|Dripstone caves ahead. Let's keep clear of the stone spikes.",
            "Здесь натёки и над нами, и под нами. Летим аккуратно.|Dripstone above and below us. Fly carefully.");
        Biome(d, "lush_caves",
            "Мы в пышных пещерах. Вот это подземный сад!|We're in lush caves. What an underground garden!",
            "Пышные пещеры! Можно поискать светящиеся ягоды.|Lush caves! We could look for glow berries.",
            "Столько зелени под землёй. Здесь хочется задержаться.|So much greenery underground. I want to linger here.",
            "В пышных пещерах можно встретить аксолотлей. Присмотримся к воде?|We might find axolotls in these lush caves. Shall we check the water?",
            "Летим через пышные пещеры. Подземный сад с высоты!|We're flying through lush caves. An underground garden from above!",
            "Среди пещерной зелени летим осторожно — потолок рядом.|Fly carefully through the cave greenery. The ceiling is close.",
            "Пышные пещеры на пути. Здесь так и хочется сделать остановку.|Lush caves ahead. This place makes me want to stop.",
            "Пролетаем через подземную зелень. Красивое место!|We're flying through underground greenery. What a lovely place!");
        Biome(d, "deep_dark",
            "Мы в тёмных глубинах. Давай потише.|We're in the deep dark. Let's keep quiet.",
            "Тёмные глубины! Лучше не тревожить скалк-крикуны.|The deep dark! Best not disturb the sculk shriekers.",
            "Здесь лишний шум может дорого обойтись. Крадёмся?|Noise could cost us dearly here. Shall we sneak?",
            "В тёмных глубинах я бы сначала наметила путь назад.|I'd plan our way back first in the deep dark.",
            "Летим через тёмные глубины. Продумай место посадки.|We're flying through the deep dark. Choose a landing spot carefully.",
            "Тёмные глубины вокруг. После посадки лучше двигаться тихо.|The deep dark surrounds us. Best move quietly once we land.",
            "Пролетаем над скалком. Не будем тревожить крикуны.|We're passing over sculk. Let's not disturb the shriekers.",
            "В тёмных глубинах даже в полёте стоит помнить о пути назад.|Even in flight, let's remember our way back through the deep dark.");
        Biome(d, "sulfur_caves",
            "Мы в серных пещерах! Интересно, встретим ли серного куба?|We're in sulfur caves! I wonder if we'll meet a sulfur cube?",
            "Серные пещеры — новое место для подземной вылазки.|Sulfur caves. A new place for an underground expedition.",
            "О, серные пещеры! Здесь хочется рассмотреть каждый уголок.|Oh, sulfur caves! I want to explore every corner.",
            "В серных пещерах поищем что-нибудь необычное. Только без спешки.|Let's look for something unusual in the sulfur caves. No rushing.",
            "Летим через серные пещеры. Сначала убедимся, что проход свободен.|We're flying through sulfur caves. Let's make sure the passage is clear.",
            "Серные пещеры на пути! Высматриваем удобное место для остановки.|Sulfur caves ahead! Let's look for a good place to stop.",
            "Пролетаем через серные пещеры. Может, заметим серного куба?|We're passing through sulfur caves. Maybe we'll spot a sulfur cube?",
            "В серных пещерах не везде хватит места для полёта. Осторожнее.|Sulfur caves won't always have room to fly. Take care.");
        Biome(d, "nether_wastes",
            "Мы в пустошах Незера. Смотри, куда наступаешь.|We're in the nether wastes. Watch your step.",
            "Пустоши Незера! Запомним путь к порталу.|The nether wastes! Let's remember the way to our portal.",
            "Здесь всё выглядит сурово. Надёжная дорога нам пригодится.|Everything looks harsh here. A safe path will come in handy.",
            "В пустошах Незера лучше держать блоки под рукой.|Best keep some blocks handy in the nether wastes.",
            "Летим через пустоши Незера. Бережём высоту над лавой.|We're flying through the nether wastes. Keep some height above the lava.",
            "Пустоши Незера вокруг. Выбираем маршрут между выступами.|Nether wastes all around. Let's navigate between the outcrops.",
            "В полёте по Незеру стоит заранее искать место для посадки.|Flying through the Nether, it's best to plan where we'll land.",
            "Пролетаем через пустоши. Не потеряем дорогу к порталу.|We're passing through the wastes. Let's keep track of our portal.");
        Biome(d, "crimson_forest",
            "Мы в багровом лесу. Необычная компания может быть рядом.|We're in a crimson forest. Unusual company may be nearby.",
            "Багровый лес! Поищем путь между огромными грибами.|A crimson forest! Let's find a path between the huge fungi.",
            "В багровом лесу красиво, но за хоглинами лучше следить.|The crimson forest is lovely, but let's watch for hoglins.",
            "Эти багровые оттенки отлично подойдут для необычной постройки.|These crimson colours would suit an unusual build.",
            "Летим через багровый лес. Между грибами бывает тесно.|We're flying through a crimson forest. The fungi can leave little room.",
            "Багровые кроны на пути. Держим свободный проход в поле зрения.|Crimson canopies ahead. Keep a clear passage in sight.",
            "Пролетаем через багровый лес. Сверху он особенно яркий.|We're passing through a crimson forest. It's especially vivid from above.",
            "В багровом лесу заранее выберем место для приземления.|Let's choose our landing spot early in the crimson forest.");
        Biome(d, "warped_forest",
            "Мы в искажённом лесу. Словно попали в другой мир внутри Незера.|We're in a warped forest. Like another world within the Nether.",
            "Искажённый лес! Какие необычные синие и зелёные оттенки.|A warped forest! Such unusual blues and greens.",
            "В искажённом лесу лучше не встречаться взглядом с эндерменами.|Best avoid meeting endermen's eyes in the warped forest.",
            "Из этой искажённой древесины можно придумать интересный дом.|This warped wood could make an interesting house.",
            "Летим через искажённый лес. Обходим огромные грибы.|We're flying through a warped forest. Keep clear of the huge fungi.",
            "Искажённый лес вокруг нас. Какой странный и красивый пейзаж!|Warped forest all around us. Such a strange and lovely landscape!",
            "Пролетаем над искажёнными кронами. Не забываем про потолок Незера.|We're passing over warped canopies. Mind the Nether's ceiling.",
            "В полёте искажённый лес выглядит совсем фантастически.|The warped forest looks otherworldly in flight.");
        Biome(d, "soul_sand_valley",
            "Мы в долине песка душ. Здесь шаги становятся тяжелее.|We're in a soul sand valley. Steps get heavier here.",
            "Долина песка душ! Хотелось бы пройти её без лишних встреч.|A soul sand valley! I'd like to cross without unwanted company.",
            "У этой долины мрачное настроение. Держим путь назад в памяти.|This valley has a gloomy mood. Let's remember the way back.",
            "На песке душ далеко не убежишь. Выберем надёжный маршрут.|We won't run far on soul sand. Let's pick a safe route.",
            "Летим через долину песка душ. Хорошо, что не приходится брести.|We're flying through a soul sand valley. Glad we don't have to trudge.",
            "Долина песка душ под нами. Следим за тем, что летает рядом.|Soul sand valley below. Watch what else is flying nearby.",
            "Пролетаем через мрачную долину. Поищем безопасную площадку.|We're passing through a gloomy valley. Let's find a safe landing spot.",
            "В полёте песок душ нас не замедляет. Осталось выбрать выход.|Soul sand can't slow us in flight. Now let's choose a way out.");
        Biome(d, "basalt_deltas",
            "Мы в базальтовых дельтах. Смотри под ноги: поверхность неровная.|We're in basalt deltas. Watch your step on the uneven ground.",
            "Базальтовые дельты! Красиво, но прогулка обещает быть непростой.|Basalt deltas! Beautiful, but not an easy walk.",
            "Между базальтовыми столбами лучше двигаться осторожно.|Best move carefully between the basalt columns.",
            "Здесь много камня и опасных промежутков. Не торопимся.|Lots of rock and dangerous gaps here. Let's take it slowly.",
            "Летим через базальтовые дельты. Не заденем столбы!|We're flying through basalt deltas. Mind the columns!",
            "Базальт и лава вокруг. Выберем просторный маршрут для полёта.|Basalt and lava all around. Let's choose a roomy flight path.",
            "Пролетаем над неровными дельтами. Посадку лучше продумать заранее.|We're passing over uneven deltas. Best plan our landing early.",
            "В базальтовых дельтах полёт требует внимания к каждому выступу.|Flying through basalt deltas means watching every outcrop.");
        Biome(d, "the_end",
            "Мы в центральной части Энда. Здесь чувствуется что-то важное.|We're in the central End. This place feels significant.",
            "Энд! Давай не будем спешить к краю острова.|The End! Let's not rush towards the island's edge.",
            "На центральном острове Энда стоит внимательно оглядеться.|It's worth looking around carefully on the End's central island.",
            "Над нами пустое небо Энда. Держимся уверенно.|The End's empty sky above us. Let's stay steady.",
            "Летим над центральной частью Энда. Следим за краем острова.|We're flying over the central End. Watch the island's edge.",
            "Центральный остров Энда под нами. Выберем место для посадки.|The End's central island is below us. Let's choose a landing spot.",
            "Пролетаем над Эндом. Не будем терять из виду твёрдую землю.|We're flying over the End. Keep solid ground in sight.",
            "С высоты центральный остров Энда особенно хорошо виден.|The End's central island is especially clear from up here.");
        Biome(d, "end_highlands",
            "Мы на возвышенностях Энда. Можно поискать города.|We're in the End highlands. We could look for cities.",
            "Возвышенности Энда! Пора осмотреть дальние острова.|The End highlands! Time to explore the outer islands.",
            "В этих возвышенностях можно встретить растения коруса.|We might find chorus plants in these highlands.",
            "Острова Энда продолжаются. Отметим обратный путь.|The End islands go on. Let's mark our way back.",
            "Под нами возвышенности Энда. Высматриваем города!|End highlands below us. Keep an eye out for cities!",
            "Летим над высокими островами Энда. Выбираем следующий ориентир.|We're flying over the End's high islands. Let's choose our next landmark.",
            "Возвышенности Энда внизу. Здесь можно поискать площадку для остановки.|End highlands below. We could look for somewhere to stop.",
            "С высоты проще осматривать дальние острова Энда.|The outer End islands are easier to survey from above.");
        Biome(d, "end_midlands",
            "Мы на средних землях Энда. Продолжим исследовать остров.|We're in the End midlands. Let's keep exploring the island.",
            "Средние земли Энда! Впереди ещё хватает простора.|The End midlands! Plenty of ground left ahead.",
            "Эти земли соединяют разные части островов. Выберем направление.|These lands connect different parts of the islands. Let's pick a direction.",
            "В Энде легко потерять ориентиры. Запомним этот участок.|It's easy to lose our bearings in the End. Let's remember this spot.",
            "Под нами средние земли Энда. Остров хорошо виден сверху.|End midlands below us. We have a clear view of the island.",
            "Летим над средними землями Энда. Наметим следующий участок.|We're flying over the End midlands. Let's choose our next area.",
            "Средние земли Энда внизу. Держимся ближе к острову.|End midlands below. Let's stay close to the island.",
            "Пролетаем над островами Энда. Где сделаем следующую остановку?|We're flying over End islands. Where shall we stop next?");
        Biome(d, "end_barrens",
            "Мы на окраинах Энда. До пустоты может быть совсем близко.|We're in the End barrens. The void may be very close.",
            "Окраины острова! Давай не подходить к самому краю.|The island's edge! Let's not get too close.",
            "Здесь земля заканчивается. Осторожнее с каждым шагом.|The ground ends here. Watch every step.",
            "На окраинах Энда лучше заранее выбрать путь обратно.|Best plan our way back in the End barrens.",
            "Под нами окраины Энда. За краем острова — пустота.|End barrens below us. Beyond the island's edge is the void.",
            "Летим вдоль края острова. Следующую посадку лучше видеть заранее.|We're flying along an island's edge. Best spot our next landing early.",
            "Окраины Энда внизу. Не теряем высоту над пустотой.|End barrens below. Don't lose height above the void.",
            "Пролетаем над краем острова. Держим сушу в поле зрения.|We're passing over an island's edge. Keep land in sight.");
        Biome(d, "small_end_islands",
            "Мы среди маленьких островов Энда. Здесь пригодятся мосты.|We're among small End islands. Bridges could be useful here.",
            "Маленькие острова! Между ними лучше не прыгать наугад.|Small islands! Best not jump between them blindly.",
            "Каждый клочок земли здесь окружён пустотой. Будем внимательны.|Every patch of land here is surrounded by void. Let's be careful.",
            "На маленьких островах Энда особенно ценишь надёжный путь.|A reliable route matters on the small End islands.",
            "Под нами маленькие острова Энда. Выбираем подходящий для посадки.|Small End islands below. Let's choose one to land on.",
            "Летим между маленькими островами. Земли здесь немного.|We're flying between small islands. Not much ground here.",
            "Крошечные острова внизу. В полёте по Энду пригодится запас высоты.|Tiny islands below. Some spare height helps when flying in the End.",
            "Над пустотой разбросаны маленькие острова. Наметим следующий.|Small islands are scattered over the void. Let's choose the next one.");
        Biome(d, "the_void",
            "Здесь биом пустоты. Совсем необычное место.|This is the void biome. A very unusual place.",
            "Биом пустоты! Сначала разберёмся, где здесь опора.|The void biome! First, let's work out where we can stand.",
            "В пустоте нет привычного пейзажа. Будем внимательны.|The void has no familiar landscape. Let's be careful.",
            "Мы в биоме пустоты. Поищем надёжный ориентир.|We're in the void biome. Let's find a reliable landmark.",
            "Летим через биом пустоты. Следим за высотой.|We're flying through the void biome. Watch our altitude.",
            "Вокруг биом пустоты. Наметим безопасное место для остановки.|The void biome surrounds us. Let's plan a safe place to stop.",
            "Полёт в пустоте — необычное путешествие. Не теряем ориентиры.|Flying through the void is an unusual journey. Keep our bearings.",
            "Мы в полёте над пустотой. Сначала найдём надёжную опору.|We're flying over the void. Let's find solid footing first.");
    }
}
