using System.Collections.Generic;

internal sealed partial class MinecraftDialogue
{
    private static void AddWaterBiomes(Dictionary<string, Line[]> d)
    {
        Biome(d, "river",
            "Мы у реки. Хорошее место для небольшой остановки.|We're by a river. A good place for a little break.",
            "Река! Может, отправимся дальше на лодке?|A river! Shall we continue by boat?",
            "Вдоль реки наверняка найдётся красивый маршрут.|There's bound to be a scenic route along this river.",
            "У реки так спокойно. Поставим здесь маленький причал?|It's peaceful by the river. Shall we build a little dock?",
            "Под нами река. Как красиво она петляет!|There's a river below us. Look at those bends!",
            "Летим над рекой. Можно проследить, куда она ведёт.|We're flying over a river. We could see where it leads.",
            "Внизу река! У берега можно поискать место для посадки.|River below! We could look for a landing spot by the bank.",
            "С высоты река похожа на длинную синюю ленту.|From up here, the river looks like a long blue ribbon.");
        Biome(d, "frozen_river",
            "Мы у замёрзшей реки. Вода спряталась подо льдом.|We're by a frozen river. The water is hidden beneath the ice.",
            "Замёрзшая река! По льду можно прокатиться на лодке.|A frozen river! We could take a boat across the ice.",
            "У этой реки зимний характер. Смотри под ноги.|This river has a wintry mood. Watch your step.",
            "Лёд тянется вдоль русла. Получилась готовая зимняя дорога.|Ice follows the riverbed. A ready-made winter road.",
            "Под нами замёрзшая река. Русло блестит льдом.|Frozen river below us. Its course is covered in ice.",
            "Летим вдоль замёрзшей реки. Красивый зимний маршрут.|We're flying along a frozen river. A lovely winter route.",
            "Внизу ледяная лента реки. На посадке будет скользко.|An icy ribbon of river below. Landing could be slippery.",
            "Сверху замёрзшую реку легко принять за ледовую дорогу.|From above, the frozen river looks like an ice road.");
        Biome(d, "beach",
            "Мы на пляже! Можно немного задержаться у воды.|We're on a beach! We could linger by the water.",
            "Песок и вода — осталось придумать домик на берегу.|Sand and water. Now we just need an idea for a beach house.",
            "На пляже удобно начать морское путешествие.|A beach is a good place to start a sea voyage.",
            "Берег! Может, поставим здесь ориентир для возвращения?|The shore! Shall we leave a landmark for our return?",
            "Под нами пляж. Песчаная полоса хорошо видна сверху.|Beach below. The sandy strip stands out from above.",
            "Летим вдоль пляжа. Поищем просторный участок для посадки.|We're flying along a beach. Let's look for an open landing spot.",
            "Внизу песчаный берег. Тут мог бы быть наш морской дом.|Sandy shore below. Our seaside home could go here.",
            "С высоты видно, как пляж отделяет сушу от воды.|From up here, we can see the beach dividing land and water.");
        Biome(d, "snowy_beach",
            "Мы на заснеженном пляже. Купание пока отложим?|We're on a snowy beach. Shall we postpone the swimming?",
            "Снег у самой воды! Необычное место для морского домика.|Snow right by the water! An unusual spot for a beach house.",
            "На этом пляже вместо тёплого песка — зимний пейзаж.|This beach offers winter scenery instead of warm sand.",
            "Заснеженный берег выглядит тихим и немного суровым.|The snowy shore looks quiet and a little rugged.",
            "Под нами заснеженный пляж. Белая полоса вдоль воды.|Snowy beach below us. A white strip along the water.",
            "Летим над зимним берегом. Поищем ровное место.|We're flying over a wintry shore. Let's look for level ground.",
            "Внизу снег встречается с морем. Красивый контраст.|Snow meets the sea below. A lovely contrast.",
            "Сверху этот пляж больше похож на край снежного одеяла.|From above, this beach looks like the edge of a snowy blanket.");
        Biome(d, "stony_shore",
            "Мы на каменистом берегу. Тут вместо песка сплошной камень.|We're on a stony shore. Rock instead of sand here.",
            "Каменистый берег! Здесь просится маяк.|A stony shore! This place is asking for a lighthouse.",
            "У воды стало каменисто. Выберем удобный проход.|It's rocky by the water. Let's pick an easy route.",
            "На таком берегу морская крепость смотрелась бы отлично.|A seaside fortress would look great on this shore.",
            "Под нами каменистый берег. Осторожнее при посадке.|Stony shore below us. Take care when landing.",
            "Летим вдоль скал у воды. Хороший вид для будущего маяка.|We're flying along rocks by the water. A fine view for a future lighthouse.",
            "Внизу камень встречается с морем. Песчаного пляжа здесь нет.|Stone meets the sea below. No sandy beach here.",
            "С высоты неровности каменистого берега особенно заметны.|The uneven stony shore really stands out from above.");
        Biome(d, "ocean",
            "Мы в океане. Куда держим курс?|We're in the ocean. Where are we headed?",
            "Океан! Надеюсь, мы запомнили дорогу к берегу.|The ocean! I hope we remembered the way back to shore.",
            "Перед нами морские просторы. Время для путешествия.|Open seas ahead. Time for a voyage.",
            "В океане хочется найти маленький остров для базы.|The ocean makes me want to find a little island for a base.",
            "Под нами океан. Воды до самого горизонта!|Ocean below us. Water all the way to the horizon!",
            "Летим над океаном. Будем присматривать сушу для остановки.|We're flying over the ocean. Let's keep an eye out for land.",
            "Внизу морской простор. Сверху удобнее искать острова.|Open sea below. Islands are easier to spot from above.",
            "Океан под нами кажется бесконечным. Не потеряем направление.|The ocean below seems endless. Let's keep our bearings.");
        Biome(d, "deep_ocean",
            "Мы в глубоком океане. Под водой есть простор для исследований.|We're in a deep ocean. Plenty of room to explore underwater.",
            "Глубокий океан! Для погружения лучше подготовиться.|A deep ocean! Best prepare before diving.",
            "Здесь океан становится глубже. Воздух под водой нужно беречь.|The ocean gets deeper here. We'll need to watch our air underwater.",
            "Интересно, что скрывает дно этого глубокого океана?|I wonder what lies on the floor of this deep ocean?",
            "Под нами глубокий океан. До дна отсюда далеко.|Deep ocean below. The seabed is a long way down.",
            "Летим над глубоким океаном. Поищем ближайший остров.|We're flying over a deep ocean. Let's look for the nearest island.",
            "Внизу глубокие воды. Для посадки лучше найти сушу.|Deep water below. Better find land to touch down.",
            "Сверху океан спокоен, а под нами целая глубина для исследований.|The ocean looks calm from above, with depths to explore below.");
        Biome(d, "cold_ocean",
            "Мы в холодном океане. У этого моря строгие цвета.|We're in a cold ocean. The sea has a sombre palette here.",
            "Холодный океан! Поищем красивый северный берег.|A cold ocean! Let's look for a scenic northern shore.",
            "В холодном океане можно встретить заросли ламинарии.|We might find kelp forests in this cold ocean.",
            "Впереди холодные морские воды. Продолжим путешествие?|Cold seas ahead. Shall we keep exploring?",
            "Под нами холодный океан. Какая глубокая синева.|Cold ocean below us. Such a deep blue.",
            "Летим над холодным океаном. Высматриваем берег.|We're flying over a cold ocean. Keep an eye out for shore.",
            "Внизу холодные воды. Здесь приятно лететь вдоль побережья.|Cold waters below. This would be a lovely coast to follow.",
            "Холодный океан под нами выглядит особенно сурово.|The cold ocean below us looks especially rugged.");
        Biome(d, "deep_cold_ocean",
            "Мы в глубоком холодном океане. Серьёзное место для погружений.|We're in a deep cold ocean. A serious place for a dive.",
            "Холодные воды уходят далеко вниз. Проверим запас воздуха.|Cold waters stretch far below. Let's check our air supply.",
            "Глубокий холодный океан! Морские исследования требуют подготовки.|A deep cold ocean! Sea exploration takes preparation.",
            "Здесь холодный океан особенно глубок. Интересно, что на дне?|The cold ocean is especially deep here. What's on the seabed?",
            "Под нами глубокий холодный океан. Поищем сушу впереди.|Deep cold ocean below. Let's look for land ahead.",
            "Летим над холодными глубинами. Держим курс.|We're flying over cold depths. Let's stay on course.",
            "Внизу глубокий холодный океан. Внушительный простор.|Deep cold ocean below. What an expanse.",
            "С высоты не видно, насколько глубоко это холодное море.|From above, we can't tell how deep this cold sea goes.");
        Biome(d, "lukewarm_ocean",
            "Мы в умеренно тёплом океане. Приятные морские оттенки.|We're in a lukewarm ocean. Lovely sea colours.",
            "Умеренно тёплый океан! Можно поискать песчаный берег.|A lukewarm ocean! We could look for a sandy shore.",
            "Эти воды так и зовут в морское путешествие.|These waters are inviting us on a sea voyage.",
            "В умеренно тёплом океане хочется задержаться и осмотреться.|This lukewarm ocean makes me want to stop and look around.",
            "Под нами умеренно тёплый океан. Красивый цвет воды!|Lukewarm ocean below us. What a lovely colour!",
            "Летим над умеренно тёплым океаном. Высматриваем острова.|We're flying over a lukewarm ocean. Let's watch for islands.",
            "Внизу спокойные морские оттенки. Хороший вид с высоты.|Soft sea colours below. A lovely view from up here.",
            "Умеренно тёплый океан под нами — отличный фон для путешествия.|The lukewarm ocean below makes a lovely backdrop for our journey.");
        Biome(d, "deep_lukewarm_ocean",
            "Мы в глубоком умеренно тёплом океане. Красиво, но до дна далеко.|We're in a deep lukewarm ocean. Lovely, but the bottom is far away.",
            "Глубокие воды! Перед погружением стоит подготовить снаряжение.|Deep waters! Best get our gear ready before diving.",
            "Здесь умеренно тёплый океан уходит далеко вниз.|The lukewarm ocean goes a long way down here.",
            "В этих глубинах наверняка найдётся что исследовать.|There must be something to explore in these depths.",
            "Под нами глубокий умеренно тёплый океан. Впереди есть суша?|Deep lukewarm ocean below us. Any land ahead?",
            "Летим над глубокими водами красивого синего оттенка.|We're flying over deep waters in a lovely shade of blue.",
            "Внизу глубокий умеренно тёплый океан. Поищем остров для привала.|Deep lukewarm ocean below. Let's find an island for a break.",
            "Сверху эти воды выглядят приветливо, но глубину не стоит забывать.|These waters look inviting from above, but let's remember their depth.");
        Biome(d, "warm_ocean",
            "Мы в тёплом океане. Можно поискать коралловые рифы!|We're in a warm ocean. We could look for coral reefs!",
            "Тёплый океан! Самое время полюбоваться подводными красками.|A warm ocean! Time to admire the underwater colours.",
            "Какая яркая вода! В тёплом океане приятно исследовать мелководье.|Such bright water! The warm ocean's shallows are lovely to explore.",
            "В тёплом океане можно встретить разноцветных тропических рыб.|We might spot colourful tropical fish in this warm ocean.",
            "Под нами тёплый океан. Высматриваем кораллы!|Warm ocean below us. Let's watch for coral!",
            "Летим над тёплым океаном. Вода здесь особенно яркая.|We're flying over a warm ocean. The water is especially bright here.",
            "Внизу тёплое море. Может, выберем место для остановки?|Warm sea below. Shall we pick a place to stop?",
            "Тёплый океан с высоты похож на открытку.|The warm ocean looks like a postcard from up here.");
        Biome(d, "frozen_ocean",
            "Мы в замёрзшем океане. Среди льда нужно выбирать путь.|We're in a frozen ocean. We'll need to navigate between the ice.",
            "Замёрзший океан! Настоящее полярное путешествие.|A frozen ocean! A real polar expedition.",
            "Лёд среди моря. Здесь получилась бы отличная полярная станция.|Ice out at sea. A great setting for a polar station.",
            "В замёрзшем океане не хочется терять дорогу домой.|I wouldn't want to lose our way home in a frozen ocean.",
            "Под нами замёрзший океан. Лёд хорошо заметен с высоты.|Frozen ocean below us. The ice stands out from above.",
            "Летим над замёрзшим океаном. Выбираем место между льдинами.|We're flying over a frozen ocean. Let's pick a spot between the ice.",
            "Внизу ледяное море. Впечатляющий зимний пейзаж.|An icy sea below. What a winter landscape.",
            "Сверху замёрзший океан похож на огромную ледяную мозаику.|From above, the frozen ocean looks like a huge ice mosaic.");
        Biome(d, "deep_frozen_ocean",
            "Мы в глубоком замёрзшем океане. Подо льдом скрывается глубина.|We're in a deep frozen ocean. Depths hide beneath the ice.",
            "Глубокий замёрзший океан! Для исследования нужен хороший план.|A deep frozen ocean! Exploring here needs a good plan.",
            "Лёд сверху, глубокое море снизу. Интересное место для экспедиции.|Ice above, deep sea below. An interesting expedition site.",
            "В этих ледяных глубинах важно помнить о пути на поверхность.|In these icy depths, let's keep our route to the surface in mind.",
            "Под нами глубокий замёрзший океан. Среди льда скрываются большие глубины.|Deep frozen ocean below us. Great depths hide among the ice.",
            "Летим над глубоким ледяным морем. Будем держаться выбранного курса.|We're flying over a deep icy sea. Let's stick to our course.",
            "Внизу глубокий замёрзший океан. Суша пригодится для привала.|Deep frozen ocean below. Land would be handy for a rest.",
            "С высоты виден лёд, но не глубины этого замёрзшего океана.|From up here we can see the ice, but not the frozen ocean's depths.");
    }
}
