using System.Collections.Generic;

internal sealed partial class MinecraftDialogue
{
    // Four complete ground/inside lines, then four complete flight lines, paired RU | EN.
    private static void Biome(Dictionary<string, Line[]> d, string id, params string[] lines)
    {
        Add(d, "biome/minecraft:" + id, lines[0], lines[1], lines[2], lines[3]);
        Add(d, "air/minecraft:" + id, lines[4], lines[5], lines[6], lines[7]);
    }

    private static void AddBiomes(Dictionary<string, Line[]> d)
    {
        Biome(d, "forest",
            "Мы в лесу, тут чудесно!|We're in a forest. It's lovely here!",
            "Лес вокруг. Древесины для наших затей должно хватить.|Forest all around. There should be plenty of wood for our plans.",
            "Среди деревьев можно устроить небольшой привал.|We could take a little break among the trees.",
            "Как насчёт уютной лесной хижины?|How about a cosy little forest cabin?",
            "Под нами лес. Сверху он похож на зелёное море.|There's a forest below us. It looks like a green sea from up here.",
            "Пролетаем над лесом. Поищем просвет для посадки?|We're flying over a forest. Shall we look for a clearing to land?",
            "Лес остаётся внизу. Люблю смотреть на кроны с высоты.|The forest is below us. I love seeing the treetops from above.",
            "Какой вид на лес! Главное — не зацепить верхушки.|What a view of the forest! Just watch out for the treetops.");
        Biome(d, "flower_forest",
            "Мы в цветочном лесу. Здесь хочется собрать букет.|We're in a flower forest. It makes me want to pick a bouquet.",
            "Цветочный лес! Можно поискать краски для нашего дома.|A flower forest! We could find colours for our home here.",
            "Деревья и цветы — прекрасное сочетание для прогулки.|Trees and flowers make a lovely setting for a walk.",
            "Давай задержимся в цветочном лесу. Он такой нарядный.|Let's linger in the flower forest. It's so colourful.",
            "Под нами цветочный лес. Красочный участок нашего пути.|There's a flower forest below. A colourful part of our journey.",
            "Летим над цветочным лесом. Вот бы рассмотреть цветы поближе.|We're flying over a flower forest. I'd love a closer look at the flowers.",
            "Внизу цветочный лес. Может, сделаем остановку?|There's a flower forest below. Shall we stop for a while?",
            "С высоты цветочный лес выглядит как сад среди деревьев.|From up here, the flower forest looks like a garden among the trees.");
        Biome(d, "birch_forest",
            "Мы в березняке. Как светло среди белых стволов!|We're in a birch forest. It's so bright among the white trunks!",
            "Берёзовый лес! Из этой древесины получится светлый дом.|A birch forest! This wood would make a bright little house.",
            "Люблю эти белые стволы с тёмными отметинами.|I love those white trunks with their dark markings.",
            "В березняке приятно немного замедлить шаг.|A birch forest is a nice place to slow down for a while.",
            "Под нами березняк. Светлые стволы прячутся под кронами.|There's a birch forest below. Pale trunks hide beneath the canopy.",
            "Пролетаем над берёзовым лесом. Хорошее место для остановки.|We're flying over a birch forest. A nice place for a stop.",
            "Березняк внизу. Запомним его, если понадобится древесина.|Birch forest below. Let's remember it if we need wood.",
            "Летим над березняком. Не будем цепляться за верхушки.|We're flying over birch trees. Let's keep clear of the treetops.");
        Biome(d, "old_growth_birch_forest",
            "Реликтовый березняк! Какие высокие деревья.|An old growth birch forest! Those trees are tall.",
            "Мы среди старых берёз. Здесь легко забыть о спешке.|We're among old birch trees. It's easy to forget about rushing here.",
            "У этого берёзового леса совсем другой размах.|This birch forest has a much grander scale.",
            "Высокие берёзы пригодятся для большой стройки.|Those tall birches could help with a big building project.",
            "Под нами реликтовый березняк. Даже сверху деревья впечатляют.|There's an old growth birch forest below. The trees are impressive even from here.",
            "Летим над высокими берёзами. Держим запас высоты.|We're flying over tall birches. Let's keep some extra height.",
            "Внизу старый берёзовый лес. Посадку лучше искать на поляне.|There's an old birch forest below. A clearing would be a better landing spot.",
            "Реликтовый березняк под нами. Прекрасный вид для путешествия.|Old growth birch forest beneath us. A lovely view for our journey.");
        Biome(d, "dark_forest",
            "Мы в тёмном лесу. Под густыми кронами стоит быть осторожнее.|We're in a dark forest. Be careful under the dense canopy.",
            "Тёмные дубы растут так тесно. Не потеряем направление.|The dark oaks grow so close together. Let's keep our bearings.",
            "Этот лес словно просит взять с собой побольше факелов.|This forest feels like a good reason to bring extra torches.",
            "В тёмном лесу можно поискать огромные грибы.|We could look for giant mushrooms in the dark forest.",
            "Под нами тёмный лес. Кроны почти скрывают землю.|There's a dark forest below. The canopy nearly hides the ground.",
            "Летим над тёмными дубами. Поищем открытое место для посадки.|We're flying over dark oaks. Let's find an open place to land.",
            "Внизу густой тёмный лес. Сверху ориентироваться проще.|Dense dark forest below. It's easier to navigate from above.",
            "Пролетаем над тёмным лесом. Интересно, что скрыто под кронами.|We're passing over a dark forest. I wonder what's beneath the canopy.");
        Biome(d, "dappled_forest",
            "Мы в пёстром лесу. Здесь будто поселилась осень.|We're in a dappled forest. It feels as though autumn has settled here.",
            "Красные, жёлтые, оранжевые тополя — какой красивый лес!|Red, yellow and orange poplars. What a beautiful forest!",
            "В пёстром лесу можно поискать грибы на стволах тополей.|We could look for shelf mushrooms on the poplars in this dappled forest.",
            "Давай запомним пёстрый лес. Отличный пейзаж для маленького лагеря.|Let's remember this dappled forest. A lovely setting for a small camp.",
            "Под нами пёстрый лес. Тополя похожи на пятна осенней краски.|There's a dappled forest below. The poplars look like splashes of autumn colour.",
            "Летим над разноцветными тополями. Вот это палитра!|We're flying over colourful poplars. What a palette!",
            "Внизу пёстрый лес. Хочется спуститься и погулять.|There's a dappled forest below. I'd love to land and wander around.",
            "Пёстрый лес с высоты особенно хорош. Найдём поляну?|The dappled forest looks wonderful from above. Shall we find a clearing?");
        Biome(d, "pale_garden",
            "Мы в бледном саду. Красиво, но немного не по себе.|We're in a pale garden. Beautiful, but a little unsettling.",
            "Бледные дубы и мох… Здесь стоит быть начеку, особенно ночью.|Pale oaks and moss… Best stay alert here, especially at night.",
            "В бледном саду лучше не забывать про скрипунов.|Best not forget about creakings in the pale garden.",
            "Этот бледный сад выглядит так, будто из него ушли краски.|This pale garden looks as though the colours have drained away.",
            "Под нами бледный сад. Светлые кроны сразу выделяются.|There's a pale garden below. The pale canopy really stands out.",
            "Летим над бледным садом. С высоты он ещё загадочнее.|We're flying over a pale garden. It looks even more mysterious from above.",
            "Внизу бледные дубы. Если сядем, будем внимательны.|Pale oaks below. If we land, let's stay alert.",
            "Бледный сад остаётся под нами. Необычный пейзаж.|The pale garden lies beneath us. What an unusual landscape.");
        Biome(d, "cherry_grove",
            "Мы в вишнёвой роще. Эти розовые кроны чудесны!|We're in a cherry grove. Those pink canopies are wonderful!",
            "Вишнёвая роща! Тут так и просится маленький домик.|A cherry grove! This place is asking for a little house.",
            "Давай немного побудем среди вишнёвых деревьев.|Let's spend a little time among the cherry trees.",
            "В розовой роще хочется устроить спокойный привал.|This pink grove makes me want to take a peaceful break.",
            "Под нами вишнёвая роща. Розовый островок среди пейзажа.|There's a cherry grove below. A pink island in the landscape.",
            "Летим над вишнёвыми кронами. Как же красиво!|We're flying over cherry blossoms. How beautiful!",
            "Вишнёвая роща внизу. Может, выберем её для остановки?|Cherry grove below. Shall we make it our next stop?",
            "Сверху вишнёвая роща похожа на розовое облако.|From above, the cherry grove looks like a pink cloud.");
        Biome(d, "plains",
            "Мы на равнине. Сколько места для строительства!|We're on the plains. So much room to build!",
            "Открытые равнины. Здесь проще выбрать направление.|Open plains. It's easier to choose a direction here.",
            "На равнине можно поискать животных для нашей фермы.|We could look for animals for our farm on the plains.",
            "Хорошее место для базы: простор и не нужно расчищать лес.|A nice place for a base: plenty of space and no forest to clear.",
            "Под нами равнины. Удобно искать место для посадки.|Plains below us. A good place to look for a landing spot.",
            "Летим над равниной. Как далеко видно!|We're flying over the plains. We can see so far!",
            "Внизу открытые поля. Можно приглядеть участок для дома.|Open fields below. We could pick out a spot for a house.",
            "С высоты равнина выглядит как огромная карта для наших планов.|From above, the plains look like a huge map for our plans.");
        Biome(d, "sunflower_plains",
            "Мы на подсолнуховых полях. Какие солнечные цветы!|We're in sunflower plains. Such cheerful flowers!",
            "Подсолнухи! Можно взять немного для сада.|Sunflowers! We could take a few for the garden.",
            "Эта равнина с подсолнухами поднимает настроение.|This sunflower-covered plain really cheers me up.",
            "В подсолнуховых полях хорошо устроить небольшую прогулку.|Sunflower plains are a lovely place for a little walk.",
            "Под нами подсолнуховые поля. Жёлтые вкрапления среди зелени.|Sunflower plains below. Yellow splashes among the green.",
            "Пролетаем над подсолнухами. Я бы здесь задержалась.|We're flying over sunflowers. I'd love to linger here.",
            "Внизу подсолнуховая равнина. Красивое место для посадки.|Sunflower plains below. A lovely place to land.",
            "Сверху поля подсолнухов особенно радуют глаз.|The sunflower fields are especially lovely from above.");
        Biome(d, "meadow",
            "Мы на лугу. Тут хочется остановиться и оглядеться.|We're in a meadow. It makes me want to stop and look around.",
            "Горный луг! Хорошее место полюбоваться окрестностями.|A mountain meadow! A lovely place to admire the surroundings.",
            "Среди луговых цветов можно устроить привал.|We could take a break among the meadow flowers.",
            "Этот луг подойдёт для домика с красивым видом.|This meadow would suit a little house with a lovely view.",
            "Под нами луг. Красивый участок среди возвышенностей.|There's a meadow below. A lovely patch among the hills.",
            "Пролетаем над лугом. Приглядим место для привала?|We're flying over a meadow. Shall we pick a place to rest?",
            "Луг внизу выглядит гостеприимно. Посадку всё равно выберем аккуратно.|The meadow below looks welcoming. Let's still choose our landing carefully.",
            "С высоты хорошо видны очертания луга.|We can see the shape of the meadow clearly from up here.");
        Biome(d, "grove",
            "Мы в заснеженной роще. Осторожнее с рыхлым снегом.|We're in a snowy grove. Watch out for powder snow.",
            "Ели среди снега — настоящий зимний пейзаж.|Spruce trees in the snow. A proper winter scene.",
            "В этой роще лучше внимательно выбирать путь между деревьями.|Let's choose our path carefully between the trees in this grove.",
            "Снежная роща уютная, пока не начинаешь проваливаться в снег.|A snowy grove is cosy until you start sinking into the snow.",
            "Под нами снежная роща. Не спеши садиться в рыхлый снег.|There's a snowy grove below. Don't rush into a powder-snow landing.",
            "Летим над заснеженными елями. Красивый зимний лес.|We're flying over snowy spruces. A beautiful winter forest.",
            "Внизу роща среди снега. Поищем твёрдое место для посадки.|There's a grove in the snow below. Let's find solid ground to land on.",
            "С высоты снежная роща похожа на зимнюю открытку.|From above, the snowy grove looks like a winter postcard.");
        Biome(d, "taiga",
            "Мы в тайге. Люблю этот хвойный пейзаж.|We're in the taiga. I love this evergreen landscape.",
            "Еловый лес! Можно поискать ягоды, только не колись о кусты.|A spruce forest! We could look for berries; mind the prickly bushes.",
            "В тайге может найтись подходящее место для деревянного дома.|We might find a nice spot for a wooden house in the taiga.",
            "Тайга вокруг. Давай не потеряем дорогу среди елей.|Taiga all around. Let's not lose our way among the spruces.",
            "Под нами тайга. Хвойный лес тянется вдаль.|There's taiga below us. Evergreen forest stretches into the distance.",
            "Летим над елями. Лучше держаться выше верхушек.|We're flying over spruces. Better stay above the treetops.",
            "Тайга внизу. Поищем поляну, если решим остановиться.|Taiga below. Let's find a clearing if we decide to stop.",
            "Сверху тайга выглядит как узор из тёмно-зелёных вершин.|From above, the taiga looks like a pattern of dark green tips.");
        Biome(d, "old_growth_pine_taiga",
            "Реликтовая сосновая тайга! Какие высокие стволы.|Old growth pine taiga! Those trunks are tall.",
            "Мы в старой сосновой тайге. Лес здесь внушительный.|We're in an old pine taiga. This forest is impressive.",
            "Среди этих сосен даже наша стройка могла бы казаться маленькой.|Even our building project might look small among these pines.",
            "Давай запомним эту тайгу, если понадобится много древесины.|Let's remember this taiga if we need plenty of wood.",
            "Под нами реликтовая сосновая тайга. Сосны будто подпирают небо.|Old growth pine taiga below. The pines seem to hold up the sky.",
            "Летим над старыми соснами. Запас высоты не помешает.|We're flying over old pines. Some extra height won't hurt.",
            "Внизу высокая сосновая тайга. Посадку ищем между деревьями.|Tall pine taiga below. Let's look for a landing between the trees.",
            "С высоты этот старый сосновый лес выглядит особенно величественно.|This old pine forest looks especially grand from above.");
        Biome(d, "old_growth_spruce_taiga",
            "Мы в реликтовой еловой тайге. Настоящие лесные великаны!|We're in old growth spruce taiga. Real forest giants!",
            "Старые ели раскинули огромные ветви. Красивое место.|The old spruces spread out huge branches. What a beautiful place.",
            "В этой тайге хочется построить дом среди больших елей.|This taiga makes me want a house among the giant spruces.",
            "Реликтовая еловая тайга впечатляет. Не потеряемся в ней.|This old growth spruce taiga is impressive. Let's not get lost.",
            "Под нами реликтовая еловая тайга. Какие широкие кроны!|Old growth spruce taiga below. Such broad canopies!",
            "Пролетаем над огромными елями. Держимся подальше от ветвей.|We're flying over giant spruces. Let's keep clear of the branches.",
            "Старый еловый лес внизу. Нужно просторное место для посадки.|Old spruce forest below. We'll need a spacious landing spot.",
            "Сверху реликтовая тайга выглядит как бесконечный хвойный ковёр.|From above, the old taiga looks like an endless evergreen carpet.");
        Biome(d, "snowy_taiga",
            "Мы в заснеженной тайге. Хвойный лес в белом наряде.|We're in snowy taiga. Evergreen forest dressed in white.",
            "Снег среди елей. Здесь получилась бы уютная зимняя база.|Snow among the spruces. This would make a cosy winter base.",
            "По снежной тайге приятно идти, если не забывать про припасы.|A snowy taiga is lovely to explore, as long as we bring supplies.",
            "Заснеженная тайга! Посмотрим, куда ведёт наш путь.|Snowy taiga! Let's see where our path leads.",
            "Под нами заснеженная тайга. Белое и зелёное до самого горизонта.|Snowy taiga below. White and green all the way to the horizon.",
            "Летим над зимним хвойным лесом. Красота!|We're flying over a winter evergreen forest. Beautiful!",
            "Внизу снежная тайга. Не будем садиться прямо в ветви.|Snowy taiga below. Let's avoid landing in the branches.",
            "С высоты заснеженные ели похожи на маленькие украшения.|From above, the snowy spruces look like little ornaments.");
        Biome(d, "snowy_plains",
            "Мы на заснеженной равнине. Сколько белого вокруг!|We're on snowy plains. So much white all around!",
            "Снежный простор. Можно поискать место для зимнего дома.|A snowy expanse. We could find a spot for a winter home.",
            "На снежной равнине хорошо видно окрестности.|We have a clear view of the surroundings on these snowy plains.",
            "Этот зимний пейзаж хочется сохранить в памяти.|I want to remember this winter landscape.",
            "Под нами заснеженные равнины. Будто летим над белым полотном.|Snowy plains below us. Like flying over a white canvas.",
            "Пролетаем над снежной равниной. Приглядим место для посадки.|We're flying over snowy plains. Let's pick out a landing spot.",
            "Внизу снежный простор. Сверху особенно хорошо виден рельеф.|A snowy expanse below. The terrain is easier to see from above.",
            "Какой вид на заснеженные равнины!|What a view of the snowy plains!");
        Biome(d, "ice_spikes",
            "Ледяные пики! Будто попали в замёрзший сказочный лес.|Ice spikes! It feels like a frozen fairy-tale forest.",
            "Мы среди ледяных столбов. Как необычно они выглядят.|We're among pillars of ice. They look so unusual.",
            "В биоме ледяных пиков можно поискать плотный лёд.|We could look for packed ice in this ice spikes biome.",
            "Давай осторожнее между ледяными пиками. Тут легко потерять направление.|Let's be careful among the ice spikes. It's easy to lose our bearings.",
            "Под нами ледяные пики. Не хочется врезаться в такой столб.|Ice spikes below us. I'd rather not crash into one of those pillars.",
            "Летим над ледяными пиками. Держим безопасную высоту.|We're flying over ice spikes. Let's keep a safe height.",
            "Сверху ледяные столбы похожи на кристаллы.|The ice pillars look like crystals from above.",
            "Внизу ледяные пики. Для посадки лучше найти свободный участок.|Ice spikes below. Better find a clear patch to land on.");
        Biome(d, "snowy_slopes",
            "Мы на заснеженных склонах. С рыхлым снегом лучше не шутить.|We're on snowy slopes. Powder snow is no joke.",
            "Снежный склон! Выбирай опору внимательно.|A snowy slope! Choose your footing carefully.",
            "Давай не будем спешить на этих заснеженных склонах.|Let's take our time on these snowy slopes.",
            "Для таких склонов пригодятся кожаные ботинки.|Leather boots would come in handy on slopes like these.",
            "Под нами снежные склоны. Место для посадки нужно выбрать с умом.|Snowy slopes below us. We'll need to choose a landing spot carefully.",
            "Летим вдоль заснеженных склонов. Не прижимайся к горе.|We're flying along snowy slopes. Keep some distance from the mountain.",
            "Внизу снежный склон. Рыхлый снег может испортить посадку.|A snowy slope below. Powder snow could spoil the landing.",
            "Сверху склоны красивые, но приземляться будем осторожно.|The slopes look lovely from above, but let's land carefully.");
        Biome(d, "frozen_peaks",
            "Мы на замёрзших вершинах. Настоящее царство льда.|We're on frozen peaks. A real kingdom of ice.",
            "Лёд и снег на вершинах. Осторожнее у обрывов.|Ice and snow on the peaks. Mind the cliff edges.",
            "До замёрзших вершин добрались. Можно полюбоваться видом.|We've reached the frozen peaks. Time to enjoy the view.",
            "Красиво здесь, но надёжная опора важнее красивого шага.|It's beautiful here, but solid footing matters more than a graceful step.",
            "Под нами замёрзшие вершины. Держись выше гребней.|Frozen peaks below. Stay above the ridges.",
            "Летим над ледяными горами. Вот это высота!|We're flying over icy mountains. What a height!",
            "Внизу замёрзшие пики. Лучше не терять скорость возле скал.|Frozen peaks below. Better keep your speed near the cliffs.",
            "С воздуха замёрзшие вершины выглядят особенно сурово.|The frozen peaks look especially rugged from the air.");
        Biome(d, "jagged_peaks",
            "Мы среди зубчатых вершин. Горы здесь с характером.|We're among jagged peaks. These mountains have character.",
            "Какие острые гребни! Давай внимательно выбирать путь.|Such sharp ridges! Let's choose our route carefully.",
            "Зубчатые вершины впечатляют. Только не подходи к краю без нужды.|These jagged peaks are impressive. Just don't get too close to the edge.",
            "Тут получилась бы крепость на вершине. Добраться бы до неё!|A mountaintop fortress would look great here. Getting there is another matter!",
            "Под нами зубчатые вершины. Оставим побольше места для манёвра.|Jagged peaks below. Let's leave plenty of room to manoeuvre.",
            "Летим над острыми гребнями. Смотри вперёд!|We're flying over sharp ridges. Keep your eyes ahead!",
            "Зубчатые пики внизу. Впечатляющая полоса препятствий.|Jagged peaks below. Quite an obstacle course.",
            "Горы под нами будто нарисованы острыми штрихами.|The mountains below look as though they were drawn with sharp strokes.");
        Biome(d, "stony_peaks",
            "Мы на каменных вершинах. Сколько открытой породы!|We're on stony peaks. So much exposed rock!",
            "Каменные горы! Здесь можно поискать полезные руды.|Stony mountains! We could look for useful ores here.",
            "На этих вершинах лучше не забывать про высоту.|Best remember how high we are on these peaks.",
            "Суровые каменные вершины. Вид отсюда должен быть отличным.|Rugged stony peaks. The view from here should be excellent.",
            "Под нами каменные вершины. Не зацепим гребень.|Stony peaks below us. Let's keep clear of the ridge.",
            "Пролетаем над открытыми скалами. Удобно осматривать горы.|We're flying over bare cliffs. A good way to survey the mountains.",
            "Каменные пики внизу. Для посадки нужен ровный уступ.|Stony peaks below. We'll need a level ledge to land on.",
            "С воздуха особенно заметны очертания каменных вершин.|The shapes of the stony peaks really stand out from the air.");
        Biome(d, "windswept_hills",
            "Мы на выветренных холмах. Рельеф здесь непростой.|We're in windswept hills. The terrain is tricky here.",
            "Холмы и каменные выступы. Не будем бежать вслепую.|Hills and rocky outcrops. Let's not run blindly ahead.",
            "На этих холмах можно выбрать место с отличным обзором.|We could find a spot with a great view on these hills.",
            "Выветренные холмы! Интересно, какой путь окажется удобнее.|Windswept hills! I wonder which route will be easiest.",
            "Под нами выветренные холмы. Сверху проще выбрать маршрут.|Windswept hills below. It's easier to choose a route from above.",
            "Летим над холмами. Следим за выступающими скалами.|We're flying over hills. Watch for jutting rocks.",
            "Внизу неровные холмы. Поищем спокойное место для посадки.|Uneven hills below. Let's find a comfortable landing spot.",
            "С высоты холмы складываются в красивый рельеф.|The hills form a lovely landscape from up here.");
        Biome(d, "windswept_gravelly_hills",
            "Мы на выветренных гравийных холмах. Под ногами много гравия.|We're in windswept gravelly hills. Plenty of gravel underfoot.",
            "Гравийные склоны! Осторожнее, если начнём копать.|Gravel slopes! Be careful if we start digging.",
            "Здесь можно запастись гравием для будущих строек.|We could stock up on gravel for future builds here.",
            "Эти голые гравийные холмы выглядят необычно.|These bare gravelly hills look unusual.",
            "Под нами гравийные холмы. Почти лунный пейзаж.|Gravelly hills below. Almost a lunar landscape.",
            "Летим над гравийными склонами. Выберем ровную площадку.|We're flying over gravel slopes. Let's pick a level patch.",
            "Внизу выветренные гравийные холмы. Хороший ориентир.|Windswept gravelly hills below. A useful landmark.",
            "С высоты хорошо видно, как гравий покрывает холмы.|From above, we can see how the gravel covers the hills.");
        Biome(d, "windswept_forest",
            "Мы в выветренном лесу. Деревья здесь соседствуют со скалами.|We're in a windswept forest. Trees and cliffs share this place.",
            "Лес на холмах! Прогулка обещает быть извилистой.|A forest on the hills! This walk could be a winding one.",
            "В выветренном лесу лучше смотреть и под ноги, и вперёд.|In a windswept forest, watch both your footing and the path ahead.",
            "На склоне среди деревьев получился бы интересный дом.|A house among the trees on a slope could be interesting.",
            "Под нами выветренный лес. Кроны повторяют очертания холмов.|A windswept forest below. The canopy follows the shape of the hills.",
            "Летим над лесистыми склонами. Держимся выше деревьев и скал.|We're flying over wooded slopes. Stay above both trees and rocks.",
            "Выветренный лес внизу. Для посадки поищем поляну.|Windswept forest below. Let's find a clearing to land in.",
            "Сверху этот лес выглядит особенно рельефным.|This forest looks especially rugged from above.");
        AddWarmBiomes(d);
        AddWaterBiomes(d);
        AddUndergroundBiomes(d);
    }

    private static void AddWarmBiomes(Dictionary<string, Line[]> d)
    {
        Biome(d, "desert",
            "Мы в пустыне. Запас еды лучше проверить заранее.|We're in a desert. Better check our food supplies early.",
            "Песок и кактусы. Давай не будем обнимать колючки.|Sand and cacti. Let's avoid hugging the prickly ones.",
            "В пустыне можно поискать храм, но сначала осмотримся.|We could look for a temple in the desert, but let's look around first.",
            "Пустынный простор. Здесь легко заметить что-нибудь вдали.|A desert expanse. It's easy to spot things in the distance here.",
            "Под нами пустыня. Песчаные просторы до горизонта.|Desert below us. Sand stretches to the horizon.",
            "Летим над пустыней. Сверху удобно искать интересные места.|We're flying over a desert. A good way to spot interesting places.",
            "Внизу песок и кактусы. Для посадки выберем участок без колючек.|Sand and cacti below. Let's land somewhere without prickles.",
            "С высоты пустыня выглядит как огромная песочная карта.|From above, the desert looks like a huge map made of sand.");
        Biome(d, "badlands",
            "Мы в бесплодных землях. Какие красивые слои терракоты!|We're in the badlands. Such beautiful layers of terracotta!",
            "Бесплодные земли! Отличное место запастись терракотой.|Badlands! A great place to stock up on terracotta.",
            "Эти цветные склоны будто сложены из полосок краски.|These colourful slopes look like stacked strips of paint.",
            "Здесь можно поискать золото, только сначала подготовимся.|We could look for gold here, but let's prepare first.",
            "Под нами бесплодные земли. Терракотовые полосы особенно заметны сверху.|Badlands below. The terracotta stripes really stand out from above.",
            "Летим над разноцветными склонами. Какой необычный пейзаж!|We're flying over colourful slopes. What an unusual landscape!",
            "Бесплодные земли внизу. Будем внимательны у обрывов.|Badlands below. Let's be careful near the cliffs.",
            "С воздуха эти терракотовые земли похожи на слоёный пирог.|From the air, these terracotta lands look like a layer cake.");
        Biome(d, "eroded_badlands",
            "Выветренные бесплодные земли! Какие причудливые столбы.|Eroded badlands! Such strange pillars.",
            "Мы среди терракотовых башен. Природа здесь постаралась.|We're among terracotta towers. Nature has been busy here.",
            "Эти выветренные скалы выглядят как декорации к приключению.|These eroded rocks look like an adventure's stage set.",
            "Между терракотовыми столбами лучше не спешить.|Let's take our time between the terracotta pillars.",
            "Под нами выветренные бесплодные земли. Целый лес каменных башен.|Eroded badlands below. A whole forest of rocky towers.",
            "Пролетаем мимо терракотовых столбов. Оставим место для манёвра.|We're passing terracotta pillars. Let's leave room to manoeuvre.",
            "Внизу терракотовые башни. Садиться на узкую вершину рискованно.|Terracotta towers below. Landing on a narrow summit would be risky.",
            "Сверху выветренные бесплодные земли выглядят совсем фантастически.|The eroded badlands look positively fantastical from above.");
        Biome(d, "wooded_badlands",
            "Мы в лесистых бесплодных землях. Деревья среди терракоты!|We're in wooded badlands. Trees among terracotta!",
            "Терракотовые склоны и дубы — необычное соседство.|Terracotta slopes and oak trees make unusual neighbours.",
            "В лесистых бесплодных землях можно запастись и деревом, и терракотой.|Wooded badlands offer both wood and terracotta.",
            "Интересное место для базы над разноцветными скалами.|An interesting place for a base above colourful cliffs.",
            "Под нами лесистые бесплодные земли. Зелёные пятна над терракотой.|Wooded badlands below. Green patches above terracotta.",
            "Летим над дубами и цветными склонами. Красивое сочетание.|We're flying over oaks and colourful slopes. A lovely combination.",
            "Внизу лесистые бесплодные земли. Поищем ровное плато.|Wooded badlands below. Let's look for a level plateau.",
            "С высоты особенно видно, где лес сменяется терракотой.|From above, it's easy to see where the forest gives way to terracotta.");
        Biome(d, "savanna",
            "Мы в саванне. Какие раскидистые акации!|We're in the savanna. Those acacias spread out so nicely!",
            "Саванна! Можно запастись оранжевой древесиной для стройки.|Savanna! We could gather orange wood for our builds.",
            "Среди акаций хочется устроить небольшой лагерь.|I'd like to set up a small camp among the acacias.",
            "Открытая саванна. Посмотрим, что интересного впереди.|Open savanna. Let's see what's interesting ahead.",
            "Под нами саванна. Акации хорошо выделяются на открытой местности.|Savanna below. The acacias stand out in the open terrain.",
            "Пролетаем над акациями. Не задень их широкие кроны.|We're flying over acacias. Watch their broad canopies.",
            "Саванна внизу. Здесь удобно искать место для остановки.|Savanna below. A handy place to look for a stop.",
            "С воздуха саванна выглядит просторно и спокойно.|From the air, the savanna looks spacious and peaceful.");
        Biome(d, "savanna_plateau",
            "Мы на плато саванны. Хорошее место оглядеть окрестности.|We're on a savanna plateau. A good place to survey the surroundings.",
            "Саванна поднялась повыше. Давай не забудем про края плато.|The savanna has risen higher. Mind the edges of the plateau.",
            "На этом плато можно придумать дом с отличным видом.|We could plan a house with a great view on this plateau.",
            "Плато среди саванны! Интересно, что видно с его края.|A plateau in the savanna! I wonder what we can see from its edge.",
            "Под нами плато саванны. Приглядим площадку для посадки.|A savanna plateau below. Let's pick out a landing area.",
            "Летим над высоким участком саванны. Следим за высотой.|We're flying over high savanna terrain. Watch our height.",
            "Плато саванны внизу. Почти готовое основание для крепости.|Savanna plateau below. Almost a ready-made foundation for a fortress.",
            "С воздуха хорошо видно, как плато поднимается над саванной.|From the air, we can see how the plateau rises above the savanna.");
        Biome(d, "windswept_savanna",
            "Выветренная саванна! Вот это причудливые скалы.|Windswept savanna! Those rocks are wonderfully strange.",
            "Мы в саванне с непростым рельефом. Смотрим под ноги.|We're in rugged savanna terrain. Watch your footing.",
            "Акации среди крутых склонов — необычный вид.|Acacias among steep slopes make an unusual sight.",
            "Эта саванна будто создана для смелой постройки на скале.|This savanna seems made for a daring clifftop build.",
            "Под нами выветренная саванна. Скалы требуют внимания.|Windswept savanna below. Those rocks need our attention.",
            "Летим над причудливыми склонами саванны. Не прижимайся к ним.|We're flying over strange savanna slopes. Keep some distance.",
            "Внизу выветренная саванна. Посадку лучше не импровизировать.|Windswept savanna below. Best not improvise the landing.",
            "С высоты эта саванна выглядит как природный лабиринт.|From above, this savanna looks like a natural maze.");
        Biome(d, "jungle",
            "Мы в джунглях. Зелень буквально со всех сторон!|We're in the jungle. Greenery everywhere!",
            "Джунгли! Можно поискать какао и арбузы.|Jungle! We could look for cocoa and melons.",
            "Среди лиан легко потерять дорогу. Запомним направление.|It's easy to lose the way among the vines. Let's remember our direction.",
            "В этих джунглях получился бы отличный дом на дереве.|These jungles would be great for a tree house.",
            "Под нами джунгли. Какой густой зелёный ковёр!|Jungle below us. Such a dense green carpet!",
            "Летим над джунглями. Держимся выше самых высоких деревьев.|We're flying over jungle. Stay above the tallest trees.",
            "Внизу джунгли. Посадка в лианы нам ни к чему.|Jungle below. Let's avoid landing in the vines.",
            "Сверху джунгли выглядят бесконечными. Поищем просвет.|The jungle looks endless from above. Let's find a clearing.");
        Biome(d, "bamboo_jungle",
            "Мы в бамбуковых зарослях. Сколько стройматериала вокруг!|We're in bamboo jungle. So much building material around!",
            "Бамбук повсюду. Может, здесь повезёт встретить панду.|Bamboo everywhere. Maybe we'll be lucky enough to meet a panda.",
            "В бамбуковых зарослях удобно пополнить запасы для подмостей.|Bamboo jungle is a good place to gather supplies for scaffolding.",
            "Эти бамбуковые заросли похожи на зелёный лабиринт.|This bamboo jungle looks like a green maze.",
            "Под нами бамбуковые заросли. Длинные стебли тянутся вверх.|Bamboo jungle below. Long stalks reach upwards.",
            "Пролетаем над бамбуком. Между стеблями садиться неудобно.|We're flying over bamboo. Landing between the stalks would be awkward.",
            "Внизу бамбуковые джунгли. Запомним место для стройматериалов.|Bamboo jungle below. Let's remember it for building supplies.",
            "С высоты бамбуковые заросли выглядят особенно густыми.|The bamboo jungle looks especially dense from above.");
        Biome(d, "sparse_jungle",
            "Мы в редких джунглях. Здесь просторнее между деревьями.|We're in sparse jungle. There's more room between the trees.",
            "Джунгли поредели. Так легче любоваться пейзажем.|The jungle has thinned out. It's easier to enjoy the scenery.",
            "В редких джунглях можно выбрать уютное место для лагеря.|We could pick a cosy campsite in the sparse jungle.",
            "Тропическая зелень без сплошной стены лиан — мне нравится.|Tropical greenery without a solid wall of vines. I like it.",
            "Под нами редкие джунгли. Видно просветы между деревьями.|Sparse jungle below. We can see gaps between the trees.",
            "Летим над редкими джунглями. Поищем удобную поляну.|We're flying over sparse jungle. Let's look for a good clearing.",
            "Внизу открытый участок джунглей. Возможное место для привала.|An open stretch of jungle below. A possible place to rest.",
            "Сверху редкие джунгли похожи на большой тропический парк.|From above, the sparse jungle looks like a big tropical park.");
        Biome(d, "swamp",
            "Мы на болоте. Не будем торопиться между водой и сушей.|We're in a swamp. Let's take our time between water and land.",
            "Болото! Здесь можно поискать кувшинки.|A swamp! We could look for lily pads here.",
            "Вода, деревья и лианы — у болота свой характер.|Water, trees and vines. The swamp has its own character.",
            "На болоте стоит внимательнее смотреть по сторонам.|Best keep a closer eye on our surroundings in the swamp.",
            "Под нами болото. Вода и суша переплетаются.|Swamp below us. Water and land weave together.",
            "Летим над болотом. Выберем сухой участок для посадки.|We're flying over a swamp. Let's pick dry ground to land on.",
            "Болото внизу. С высоты проще рассмотреть проходы.|Swamp below. It's easier to spot routes from above.",
            "Сверху болотный пейзаж похож на зелёную мозаику.|From above, the swamp looks like a green mosaic.");
        Biome(d, "mangrove_swamp",
            "Мы в мангровом болоте. Какие переплетённые корни!|We're in a mangrove swamp. Those roots are tangled!",
            "Мангровые деревья! Можно запастись древесиной красивого красного оттенка.|Mangrove trees! We could gather wood with a lovely red colour.",
            "Между мангровыми корнями путь придётся выбирать внимательно.|We'll need to choose our path carefully among the mangrove roots.",
            "В мангровом болоте хватает грязи для новых строительных идей.|The mangrove swamp has plenty of mud for new building ideas.",
            "Под нами мангровое болото. Густые кроны скрывают корни.|Mangrove swamp below. Dense canopies hide the roots.",
            "Летим над манграми. Поищем место без густых ветвей.|We're flying over mangroves. Let's find somewhere clear of thick branches.",
            "Внизу мангровый лабиринт. Сверху маршрут выбрать проще.|A mangrove maze below. Picking a route is easier from above.",
            "Мангровое болото с высоты выглядит как сплошное зелёное полотно.|From above, the mangrove swamp looks like an unbroken green canvas.");
        Biome(d, "mushroom_fields",
            "Мы на грибных полях! Какой необычный островок мира.|We're in mushroom fields! Such an unusual corner of the world.",
            "Гигантские грибы! Теперь хочется построить сказочный дом.|Giant mushrooms! Now I want to build a fairy-tale house.",
            "На грибных полях можно поискать грибных коров.|We could look for mooshrooms in these mushroom fields.",
            "Грибные поля стоит запомнить. Такие места приятно находить.|Let's remember these mushroom fields. Places like this are a lovely find.",
            "Под нами грибные поля. Грибы хорошо заметны с высоты.|Mushroom fields below. The mushrooms stand out from up here.",
            "Летим над грибными полями. Вот это находка!|We're flying over mushroom fields. What a find!",
            "Грибные поля внизу. Может, сделаем здесь остановку?|Mushroom fields below. Shall we make a stop here?",
            "Сверху огромные грибы похожи на маленькие зонтики.|From above, the giant mushrooms look like little umbrellas.");
    }
}
