"""Restore dropped localization payloads, preserving AssetRipper's GUIDs/IDs."""
import json
import re
import struct
import subprocess
from collections import defaultdict, Counter
from pathlib import Path
import UnityPy
import yaml

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "project/Assets"
DATA = ROOT / "steam-source/MateEngineX_Data"
READ = ROOT / "inspection/serialized-original"
report = json.loads((READ / "report.json").read_text())
if any("error" in row for row in report):
    raise RuntimeError("Original data must be read completely before restoration")
env = UnityPy.load(*map(str, [DATA / "globalgamemanagers.assets", DATA / "sharedassets0.assets", DATA / "level0"] + sorted((DATA / "StreamingAssets/aa/StandaloneWindows64").glob("*.bundle"))))
objects = {(o.assets_file.name, o.path_id): o for o in env.objects}
HEAD = re.compile(r"^--- !u!(\d+) &(-?\d+)(?: stripped)?$", re.M)

def docs(path):
    text = path.read_text()
    headers = list(HEAD.finditer(text))
    result = {}
    for index, match in enumerate(headers):
        end = headers[index + 1].start() if index + 1 < len(headers) else len(text)
        body = text[match.end():end].lstrip("\n")
        parsed = yaml.load(body, Loader=getattr(yaml, "CSafeLoader", yaml.SafeLoader))
        result[int(match[2])] = (int(match[1]), next(iter(parsed.values())), match.end(), end)
    return text, result

scene = ASSETS / "MATE ENGINE - Scenes/Mate Engine Update.unity"
scene_text, scene_docs = docs(scene)
print("Scene parsed", flush=True)
fileids = {}
def script_name(obj):
    script = obj.parse_monobehaviour_head().m_Script.read()
    return (script.m_Namespace + "." if script.m_Namespace else "") + script.m_ClassName

for (filename, ident), obj in objects.items():
    if filename != "level0" or obj.type.name != "MonoBehaviour" or ident not in scene_docs: continue
    script = scene_docs[ident][1].get("m_Script", {})
    if script.get("fileID") == 11500000: continue
    fileids[script_name(obj)] = script.get("fileID")

# Prefab file IDs are regenerated by AssetRipper. Match their hierarchy and
# component type, not raw IDs or ambiguous leaf names such as "Text".
def source_hierarchy(filename):
    gos, parents, components, siblings = {}, {}, {}, {}
    for (file, ident), obj in objects.items():
        if file != filename: continue
        if obj.type.name == "GameObject":
            value = obj.read()
            gos[ident] = value.m_Name
            components[ident] = [pair.component.path_id for pair in value.m_Component]
        elif obj.type.name in ("Transform", "RectTransform"):
            value = obj.read()
            parents[value.m_GameObject.path_id] = value.m_Father.path_id
            for index, child in enumerate(value.m_Children): siblings[child.path_id] = index
    transforms = {}
    go_transforms = {}
    for (file, ident), obj in objects.items():
        if file == filename and obj.type.name in ("Transform", "RectTransform"):
            transforms[ident] = obj.read().m_GameObject.path_id
            go_transforms[transforms[ident]] = ident
    def path(go):
        parent = transforms.get(parents.get(go, 0))
        return (path(parent) if parent else ()) + ((gos[go], siblings.get(go_transforms[go], 0)),)
    return gos, components, path

gos, components, source_path = source_hierarchy("sharedassets0.assets")
locations = {}
prefab_documents = {}
for prefab in sorted((ASSETS / "GameObject").glob("*.prefab")):
    text, entries = docs(prefab)
    prefab_documents[prefab] = (text, entries)
    transforms = {ident: entry[1] for ident, entry in entries.items() if entry[0] in (4, 224)}
    parents = {entry["m_GameObject"]["fileID"]: transforms.get(entry["m_Father"]["fileID"], {}).get("m_GameObject", {}).get("fileID") for entry in transforms.values()}
    siblings = {transforms[child["fileID"]]["m_GameObject"]["fileID"]: index for entry in transforms.values() for index, child in enumerate(entry["m_Children"])}
    def path(go):
        parent = parents.get(go)
        return (path(parent) if parent else ()) + ((entries[go][1]["m_Name"], siblings.get(go, 0)),)
    target_gos = defaultdict(list)
    for ident, entry in entries.items():
        if entry[0] == 1: target_gos[path(ident)].append(ident)
    guid = re.search(r"^guid: (\w+)$", Path(str(prefab) + ".meta").read_text(), re.M)[1]
    for go in gos:
        candidates = target_gos.get(source_path(go), [])
        if len(candidates) != 1: continue
        target_go = candidates[0]
        locations[("sharedassets0.assets", go)] = (prefab, target_go, guid)
        unused = [item["component"]["fileID"] for item in entries[target_go][1]["m_Component"]]
        for ident in components[go]:
            original = objects[("sharedassets0.assets", ident)]
            typeid = original.type.value
            script = None
            if typeid == 114:
                name = script_name(original)
                script = fileids.get(name)
                if script is None:
                    namespace, _, classname = name.rpartition(".")
                    digest = subprocess.check_output(["openssl", "dgst", "-md4", "-provider", "legacy", "-binary"], input=b"s\0\0\0" + namespace.encode() + classname.encode())
                    script = fileids[name] = struct.unpack("<i", digest[:4])[0]
            matches = [target for target in unused if entries[target][0] == typeid and
                       (typeid != 114 or entries[target][1].get("m_Script", {}).get("fileID") == script)]
            if len(matches) == 1:
                target = matches[0]
                locations[("sharedassets0.assets", ident)] = (prefab, target, guid)
                unused.remove(target)

named_assets = defaultdict(list)
for path in ASSETS.rglob("*.asset"):
    with path.open() as source:
        first = source.read(100)
    if "--- !u!114" not in first: continue
    text, entries = docs(path)
    if 11400000 in entries:
        name = entries[11400000][1].get("m_Name")
        if name: named_assets[name].append((path, text, entries))
print("Prefab and asset references indexed", flush=True)

def asset_location(obj):
    name = obj.parse_monobehaviour_head().m_Name if obj.type.name == "MonoBehaviour" else obj.peek_name()
    candidates = named_assets.get(name, [])
    if len(candidates) != 1: raise RuntimeError(f"Ambiguous named asset {name}: {len(candidates)}, {obj.assets_file.name}:{obj.path_id}")
    path, text, entries = candidates[0]
    guid = re.search(r"^guid: (\w+)$", Path(str(path) + ".meta").read_text(), re.M)[1]
    return path, 11400000, guid

def convert(value, original, target_path):
    if isinstance(value, dict):
        if set(value) == {"m_FileID", "m_PathID"}:
            ident = value["m_PathID"]
            if not ident: return {"fileID": 0}
            pointer = UnityPy.classes.PPtr(m_FileID=value["m_FileID"], m_PathID=ident, assetsfile=original.assets_file)
            referent = pointer.deref()
            key = (referent.assets_file.name, referent.path_id)
            if key[0] == "level0":
                if referent.path_id not in scene_docs: raise RuntimeError(f"Missing scene object {key}")
                return {"fileID": referent.path_id}
            path, target_id, guid = locations.get(key) or asset_location(referent)
            result = {"fileID": target_id}
            if path != target_path:
                native = "NativeFormatImporter:" in Path(str(path) + ".meta").read_text()
                result.update(guid=guid, type=2 if native else 3)
            return result
        return {key: convert(item, original, target_path) for key, item in value.items()}
    if isinstance(value, list): return [convert(item, original, target_path) for item in value]
    return value

changes = defaultdict(dict)
for row in report:
    original = objects[(row["file"], row["path_id"])]
    if row["file"] == "level0":
        target, ident = scene, row["path_id"]
        text, entries = scene_text, scene_docs
    elif (row["file"], row["path_id"]) in locations:
        target, ident, _ = locations[(row["file"], row["path_id"])]
        text, entries = prefab_documents[target]
    else:
        target, ident, _ = asset_location(original)
        text, entries = docs(target)
    tree = json.loads((READ / row["json"]).read_text())
    header = entries[ident][1]
    data = {key: convert(value, original, target) for key, value in tree.items() if key not in ("m_GameObject", "m_Enabled", "m_Script", "m_Name")}
    restored = dict(header)
    restored.update(data)
    body = yaml.safe_dump({"MonoBehaviour": restored}, allow_unicode=True, sort_keys=False, width=10000)
    changes[target][ident] = body

# Resolve every pointer and target before writing any file.
for path, updates in changes.items():
    text, entries = docs(path)
    for ident in sorted(updates, key=lambda key: entries[key][2], reverse=True):
        _, _, begin, end = entries[ident]
        text = text[:begin] + "\n" + updates[ident] + text[end:]
    path.write_text(text)
result = {"objects": len(report), "files": {str(path.relative_to(ASSETS)): len(updates) for path, updates in changes.items()}}
(ROOT / "inspection/localization-restoration.json").write_text(json.dumps(result, indent=2))
print(json.dumps(result, indent=2))
